from setuptools import setup, find_packages

setup(
    name="tuningfork",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "psycopg2-binary",
        "mysql-connector-python",
        "pyodbc",
        "paramiko",
        "boto3",
        "azure-identity",
        "azure-mgmt-compute",
        "google-cloud-compute",
        "matplotlib",
        "seaborn",
        "jinja2",
        "click",
    ],
    entry_points={
        "console_scripts": [
            "tuningfork=tuningfork.cli:main",
        ],
    },
    python_requires=">=3.7",
    author="Your Name",
    author_email="your.email@example.com",
    description="A tool for optimizing database performance",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/tuningfork",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Intended Audience :: System Administrators",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Topic :: Database",
        "Topic :: System :: Systems Administration",
    ],
)